# Generated by Django 4.1 on 2022-09-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_characteristics_options_monitoring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring',
            old_name='mosvla',
            new_name='movida',
        ),
        migrations.RenameField(
            model_name='monitoring',
            old_name='wasvla',
            new_name='wavida',
        ),
    ]
